spring.application.name=MicroServiceDesign

#spring.security.user.name =virendra
#spring.security.user.password=vierndra12

#  security
# In memory user,


resilience4j.circuitbreaker:
  instances:
    myCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3